/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 1BestCsharp
 */
//import package1.*;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Date;
import java.util.Properties;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

public class AddExpense extends javax.swing.JFrame {

   Connection con = null;
   PreparedStatement ps = null;
   ResultSet rs = null;
  // String uname;
   PreparedStatement pst = null;
 
  
   
    public AddExpense() {
        initComponents();
        
        
        
    }
    
    Connection cont;
    PreparedStatement psa;
    
    public AddExpense(String email){
        initComponents();
    }
    public boolean checksend;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelClose = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_DisplayExp = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jButton_AddBudg = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextField_User1 = new javax.swing.JTextField();
        jTextField_budget1 = new javax.swing.JTextField();
        jButton_ShowBud = new javax.swing.JButton();
        jTextField_Showbud1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_User = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jCombCat = new javax.swing.JComboBox();
        jTextField_LN = new javax.swing.JTextField();
        jTextField_UN = new javax.swing.JTextField();
        jButton_Addexp = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField_User2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jButton_PDF = new javax.swing.JButton();
        jButton_Showdata = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jCombCat1 = new javax.swing.JComboBox();
        jLabel_CalcTot = new javax.swing.JLabel();
        jButton_View = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel_Avbudget = new javax.swing.JLabel();
        Checkbool = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(248, 148, 6));

        jLabelClose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText("X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Expense Report System");

        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setText("-");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMin)
                .addGap(18, 18, 18)
                .addComponent(jLabelClose)
                .addGap(21, 21, 21))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addComponent(jLabel2)
                    .addContainerGap(302, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMin, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jLabelClose))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable_DisplayExp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Date", "Category", "Amount", "Description"
            }
        ));
        jTable_DisplayExp.setToolTipText("");
        jScrollPane1.setViewportView(jTable_DisplayExp);

        jTabbedPane1.setBackground(new java.awt.Color(248, 148, 6));

        jPanel3.setBackground(new java.awt.Color(44, 62, 80));

        jButton_AddBudg.setBackground(new java.awt.Color(34, 167, 240));
        jButton_AddBudg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_AddBudg.setForeground(new java.awt.Color(255, 255, 255));
        jButton_AddBudg.setText("Add Budget");
        jButton_AddBudg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddBudgActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(236, 240, 241));
        jLabel10.setText("Username");

        jTextField_User1.setBackground(new java.awt.Color(108, 122, 137));
        jTextField_User1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_User1.setForeground(new java.awt.Color(228, 241, 254));
        jTextField_User1.setEnabled(false);

        jTextField_budget1.setBackground(new java.awt.Color(108, 122, 137));
        jTextField_budget1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_budget1.setForeground(new java.awt.Color(228, 241, 254));

        jButton_ShowBud.setBackground(new java.awt.Color(34, 167, 240));
        jButton_ShowBud.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_ShowBud.setForeground(new java.awt.Color(255, 255, 255));
        jButton_ShowBud.setText("Show Budget");
        jButton_ShowBud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ShowBudActionPerformed(evt);
            }
        });
        jButton_ShowBud.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton_ShowBudKeyReleased(evt);
            }
        });

        jTextField_Showbud1.setBackground(new java.awt.Color(108, 122, 137));
        jTextField_Showbud1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField_Showbud1.setForeground(new java.awt.Color(228, 241, 254));
        jTextField_Showbud1.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(236, 240, 241));
        jLabel14.setText("Budget");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_AddBudg)
                        .addGap(75, 75, 75))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_budget1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addComponent(jTextField_User1)
                            .addComponent(jTextField_Showbud1))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_ShowBud)
                .addGap(71, 71, 71))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jLabel14)
                    .addContainerGap(261, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField_User1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jTextField_budget1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_AddBudg, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jTextField_Showbud1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_ShowBud, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(85, 85, 85)
                    .addComponent(jLabel14)
                    .addContainerGap(254, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Add Budget", jPanel3);

        jPanel4.setBackground(new java.awt.Color(44, 62, 80));
        jPanel4.setDoubleBuffered(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(236, 240, 241));
        jLabel8.setText("Username");

        jTextField_User.setBackground(new java.awt.Color(108, 122, 137));
        jTextField_User.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_User.setForeground(new java.awt.Color(228, 241, 254));
        jTextField_User.setEnabled(false);

        jDateChooser1.setDateFormatString("yyy-MM-dd");

        jCombCat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Food", "Social life", "Self Devlopment", "Transportation","House Hold","Health","Education","Gift","Other" }));

        jTextField_LN.setBackground(new java.awt.Color(108, 122, 137));
        jTextField_LN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_LN.setForeground(new java.awt.Color(228, 241, 254));

        jTextField_UN.setBackground(new java.awt.Color(108, 122, 137));
        jTextField_UN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_UN.setForeground(new java.awt.Color(228, 241, 254));

        jButton_Addexp.setBackground(new java.awt.Color(34, 167, 240));
        jButton_Addexp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Addexp.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Addexp.setText("Add Expense");
        jButton_Addexp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddexpActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(236, 240, 241));
        jLabel11.setText("Date");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(236, 240, 241));
        jLabel12.setText("Amount");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(236, 240, 241));
        jLabel13.setText("Category");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(236, 240, 241));
        jLabel16.setText("Description");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCombCat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_User, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_LN))
                    .addComponent(jButton_Addexp)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jTextField_UN)))
                .addGap(0, 27, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField_User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jCombCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_LN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(13, 13, 13)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jTextField_UN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(jButton_Addexp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Add Expense", jPanel4);

        jPanel5.setBackground(new java.awt.Color(44, 62, 80));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(236, 240, 241));
        jLabel9.setText("Username");

        jTextField_User2.setBackground(new java.awt.Color(108, 122, 137));
        jTextField_User2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_User2.setForeground(new java.awt.Color(228, 241, 254));
        jTextField_User2.setEnabled(false);
        jTextField_User2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_User2ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(236, 240, 241));
        jLabel15.setText("From Date");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(236, 240, 241));
        jLabel19.setText("To Date");

        jDateChooser2.setDateFormatString("yyy-MM-dd");

        jDateChooser3.setDateFormatString("yyy-MM-dd");

        jButton_PDF.setBackground(new java.awt.Color(34, 167, 240));
        jButton_PDF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_PDF.setForeground(new java.awt.Color(255, 255, 255));
        jButton_PDF.setText("Downlad PDF");
        jButton_PDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PDFActionPerformed(evt);
            }
        });

        jButton_Showdata.setBackground(new java.awt.Color(34, 167, 240));
        jButton_Showdata.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Showdata.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Showdata.setText("Show Data");
        jButton_Showdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ShowdataActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(236, 240, 241));
        jLabel20.setText("Category");

        jCombCat1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"All", "Food", "Social life", "Self Devlopment", "Transportation","House Hold","Health","Education","Gift","Other" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCombCat1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(25, 25, 25))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jButton_Showdata)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_PDF))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_User2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooser3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(27, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField_User2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jCombCat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_PDF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Showdata, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93))
        );

        jTabbedPane1.addTab("Report", jPanel5);

        jLabel_CalcTot.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_CalcTot.setForeground(new java.awt.Color(236, 240, 241));
        jLabel_CalcTot.setText("0");

        jButton_View.setBackground(new java.awt.Color(34, 167, 240));
        jButton_View.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_View.setForeground(new java.awt.Color(255, 255, 255));
        jButton_View.setText("View");
        jButton_View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ViewActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(236, 240, 241));
        jLabel17.setText("Total Expense");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(236, 240, 241));
        jLabel18.setText("Avilable Budget");

        jLabel_Avbudget.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_Avbudget.setForeground(new java.awt.Color(236, 240, 241));
        jLabel_Avbudget.setText("0");

        Checkbool.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Checkbool.setForeground(new java.awt.Color(236, 240, 241));
        Checkbool.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton_View, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 954, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_CalcTot, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Avbudget, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(Checkbool, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_View, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_CalcTot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17)
                        .addComponent(jLabel18)
                        .addComponent(jLabel_Avbudget, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Checkbool, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked

        System.exit(0);

    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked

        this.setState(JFrame.ICONIFIED);

    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jButton_AddBudgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddBudgActionPerformed
        
        
         String useremail = jTextField_User1.getText();
         String budget = jTextField_budget1.getText();

        if(budget.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please put budget");
        }

        else{

            try {
                String query = "UPDATE `user` SET `sentmail`=0 ,`budget`= ? WHERE `email` = ?";
                pst = MyConnection.getConnection().prepareStatement(query);
               
              
                pst.setString(1, budget);
                pst.setString(2, useremail);
                pst.executeUpdate(); 
              
              
                JOptionPane.showMessageDialog(null, "Inserted Sucessfully");

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_jButton_AddBudgActionPerformed

    
   

    public void jButton_ShowBudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ShowBudActionPerformed
   
       
        String useremail = jTextField_User1.getText();
            try {
                String query = "SELECT budget FROM `user` WHERE email = '"+ useremail +"'";
                pst = MyConnection.getConnection().prepareStatement(query);
                ResultSet resultSet = pst.executeQuery();
             if(resultSet.next()){
                 String budget = resultSet.getString(1);
                    jTextField_Showbud1.setText(budget);

                }
             else {
                 JOptionPane.showMessageDialog(null, "No Result Found ");
             }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
                
        
    }//GEN-LAST:event_jButton_ShowBudActionPerformed

    private void jButton_ShowBudKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_ShowBudKeyReleased
        if(jTextField_User1.getText().length() == 0){
            jTextField_Showbud1.setText("");
        }
    }//GEN-LAST:event_jButton_ShowBudKeyReleased

    private void jButton_AddexpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddexpActionPerformed

        String date = jDateChooser1.getDateFormatString();
        String cat = jCombCat.getSelectedItem().toString();
        String amount = jTextField_LN.getText();
        String des = jTextField_UN.getText();
        //      String useremail = jTextField_User.getText();

        if(date.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Select Date");
        }

        else if(cat.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Select Category");
        }

        else{

            try {
                String query = "INSERT INTO `addexp`( `date`, `category`, `amount`, `des`, `email`) VALUES (?, ?, ?, ?,? )";
                ps = MyConnection.getConnection().prepareStatement(query);

                ps.setString(1, ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText());
                ps.setString(2, cat);
                ps.setString(3, amount);
                ps.setString(4, des);
                ps.setString(5, jTextField_User.getText());
                //
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Inserted Sucessfully");

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_jButton_AddexpActionPerformed

    private void update_table(){
        try {  
                   String useremail = jTextField_User.getText(); 
                String query = "SELECT * FROM `addexp` WHERE email = '"+ useremail +"'";
     
                pst = MyConnection.getConnection().prepareStatement(query);
                ResultSet rst = pst.executeQuery(query);
                jTable_DisplayExp.setModel(DbUtils.resultSetToTableModel(rst));
    }
        catch(SQLException e){
             JOptionPane.showMessageDialog(null, e);
        }
    }
    
 
    public void jButton_ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ViewActionPerformed
         
       // jButton_View.setEnabled(false);
        String useremail = jTextField_User.getText(); 
         try {  
             
             String querys = "Select sentmail from `user` where email = '"+useremail+"'";
              pst = MyConnection.getConnection().prepareStatement(querys);
                ResultSet rste = pst.executeQuery(querys);
                 rste.next();
                checksend = rste.getBoolean("sentmail");
                Checkbool.setText(Boolean.toString(checksend));
                 
                String query = "SELECT * FROM `addexp` WHERE email = '"+ useremail +"'";
     
                pst = MyConnection.getConnection().prepareStatement(query);
                ResultSet rst = pst.executeQuery(query);
             
                while(rst.next())
                {
                    String expid = String.valueOf(rst.getInt("expid"));
                    String date = rst.getString("date");
                    String category = rst.getString("category");
                    String amount = rst.getString("amount");
                    String des = rst.getString("des");
                    String tbData[] = {expid,date,category,amount,des};
                    DefaultTableModel tblModel = (DefaultTableModel)jTable_DisplayExp.getModel();
                    tblModel.addRow(tbData);

                }
              } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
    update_table();
    getSum();
    GetAvBudget();
   if(checksend == false){
        try {
                String updateing = "update `user` set sentmail = 1 where email = '"+useremail+"'";
                pst = MyConnection.getConnection().prepareStatement(updateing);
               
              
                pst.executeUpdate(); 
              
              
               // JOptionPane.showMessageDialog(null, "Inserted Sucessfully");

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
       
        send_mail();
   }
   
   
    }//GEN-LAST:event_jButton_ViewActionPerformed

    private void jButton_ShowdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ShowdataActionPerformed
       String date2 = ((JTextField)jDateChooser2.getDateEditor().getUiComponent()).getText();
       String date3 = ((JTextField)jDateChooser3.getDateEditor().getUiComponent()).getText();
       String useremail = jTextField_User2.getText();
       String cate = jCombCat1.getSelectedItem().toString();
      if(cate.equals("All"))
        {
            cleartable();
            try {  
                 
                String query = "SELECT *FROM `addexp` WHERE email = '"+ useremail +"' AND date BETWEEN '"+date2+"' AND '"+date3+"'";
     
                pst = MyConnection.getConnection().prepareStatement(query);
                ResultSet rst = pst.executeQuery(query);
             
                while(rst.next())
                {
                    String expid = String.valueOf(rst.getInt("expid"));
                    String date = rst.getString("date");
                    String category = rst.getString("category");
                    String amount = rst.getString("amount");
                    String des = rst.getString("des");
                    String tbData[] = {expid,date,category,amount,des};
                    DefaultTableModel tblModel = (DefaultTableModel)jTable_DisplayExp.getModel();
                    tblModel.addRow(tbData);

                }
              } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
               
            }
             update_showdata();
             getSum();
        }
      else
      { 
          cleartable();
          try {  
                 
                String query = "SELECT *FROM `addexp` WHERE email = '"+ useremail +"' AND date BETWEEN '"+date2+"' AND '"+date3+"' AND category = '"+cate+"'";
     
                pst = MyConnection.getConnection().prepareStatement(query);
                ResultSet rst = pst.executeQuery(query);
             
                while(rst.next())
                {
                    String expid = String.valueOf(rst.getInt("expid"));
                    String date = rst.getString("date");
                    String category = rst.getString("category");
                    String amount = rst.getString("amount");
                    String des = rst.getString("des");
                    String tbData[] = {expid,date,category,amount,des};
                    DefaultTableModel tblModel = (DefaultTableModel)jTable_DisplayExp.getModel();
                    tblModel.addRow(tbData);

                }
              } catch (SQLException ex) {
                //JOptionPane.showMessageDialog(null, ex);
            }
            update_showdata();
            getSum();
      }
    
    }//GEN-LAST:event_jButton_ShowdataActionPerformed
   private void update_showdata()
    {
          String date2 = ((JTextField)jDateChooser2.getDateEditor().getUiComponent()).getText();
          String date3 = ((JTextField)jDateChooser3.getDateEditor().getUiComponent()).getText();
          String useremail = jTextField_User2.getText();
          String cate = jCombCat1.getSelectedItem().toString();
        if(cate.equals("All"))
        {
            try {  
                   
                 String query = "SELECT *FROM `addexp` WHERE email = '"+ useremail +"' AND date BETWEEN '"+date2+"' AND '"+date3+"'";
     
                pst = MyConnection.getConnection().prepareStatement(query);
                ResultSet rst = pst.executeQuery(query);
                jTable_DisplayExp.setModel(DbUtils.resultSetToTableModel(rst));
    }
        catch(SQLException e){
             //JOptionPane.showMessageDialog(null, e);
        }
        }
        else {
             try {  
                   
                 String query = "SELECT *FROM `addexp` WHERE email = '"+ useremail +"' AND date BETWEEN '"+date2+"' AND '"+date3+"' AND cate = '"+cate+"'";
     
                pst = MyConnection.getConnection().prepareStatement(query);
                ResultSet rst = pst.executeQuery(query);
                jTable_DisplayExp.setModel(DbUtils.resultSetToTableModel(rst));
    }
        catch(SQLException e){
            // JOptionPane.showMessageDialog(null, e);
        }
        }
    }
    private void jTextField_User2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_User2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_User2ActionPerformed
    public void cleartable()
    {
        jTable_DisplayExp.setModel(new DefaultTableModel(null,new String[] {"expid","date","category","amount","des"}));
    }
    private void jButton_PDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PDFActionPerformed
    try {
            String date2 = ((JTextField)jDateChooser2.getDateEditor().getUiComponent()).getText();
            String date3 = ((JTextField)jDateChooser3.getDateEditor().getUiComponent()).getText();
            String useremail = jTextField_User2.getText();
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/javamini","root","");
            JasperDesign jdesign = JRXmlLoader.load("H:\\javamini\\ExpenseReport\\src\\report2.jrxml");
             String query = "SELECT *FROM `addexp` WHERE email = '"+ useremail +"' AND date BETWEEN '"+date2+"' AND '"+date3+"'";
            
            JRDesignQuery updateQuery = new JRDesignQuery();
            updateQuery.setText(query);
            
            jdesign.setQuery(updateQuery);
            JasperReport jreport = JasperCompileManager.compileReport(jdesign);
            JasperPrint jprint = JasperFillManager.fillReport(jreport,null,conn);
            JasperViewer.viewReport(jprint);
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddExpense.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddExpense.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(AddExpense.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_PDFActionPerformed
    public void getSum()
    {
         int sum = 0;
         for(int i = 0; i< jTable_DisplayExp.getRowCount() ; i++)
         {
             sum = sum + Integer.parseInt(jTable_DisplayExp.getValueAt(i,3).toString());
         }
        jLabel_CalcTot.setText(Integer.toString(sum));
//          int bud = Integer.parseInt(jTextField_Showbud1.getText()) - sum ;
//          jLabel_Avbudget.setText(Integer.toString(bud));
          
    }
    public void GetAvBudget()
    {
        int bud = Integer.parseInt(jTextField_Showbud1.getText()) - Integer.parseInt(jLabel_CalcTot.getText()) ;
          jLabel_Avbudget.setText(Integer.toString(bud));
    }
    public void send_mail()
    {
        
        String x = jTextField_Showbud1.getText();
        int ab = Integer.parseInt(jLabel_Avbudget.getText());
        int y = Integer.parseInt(x);
        int z = y/2;
        
       
        if(ab<z)
        {
                 String semail = jTextField_User1.getText();
        try{
            Connection cont = DriverManager.getConnection("jdbc:mysql://localhost/javamini", "root", "");
            Statement stmt = cont.createStatement();
            String query = "SELECT `email` FROM `user` WHERE email='"+semail+"'";
           ResultSet rsp =  stmt.executeQuery(query);
           if(rsp.next())
           {    
              
        
        String host = "smtp.gmail.com";
        String user ="anmolagnihotri0311@gmail.com";
        String pass="agnihotri0311";
        String to = jTextField_User1.getText();
        String subject="Budget Alert";
        String message ="Your 50% Budget has been used your remaing budget is  "+ab;
        boolean sessionDebug = false;
        Properties pros = System.getProperties();
        pros.put("mail.smtp.auth","true");
        pros.put("mail.smtp.starttls.enable", "true");
        pros.put("mail.smtp.host", "host");
        pros.put("mail.smtp.port","587");
        pros.put("mail.smtp.starttls.required", "true");
        java.security.Security.addProvider(new com.sun.net.ssl.internal.ssl.Provider());
        Session mailSession = Session.getDefaultInstance(pros, null);
        mailSession.setDebug(sessionDebug);
        Message msg = new MimeMessage(mailSession);
        msg.setFrom(new InternetAddress(user));
        InternetAddress [] address = {new InternetAddress(to)};
        msg.setRecipients(Message.RecipientType.TO, address);
        msg.setSubject(subject);
        msg.setText(message);
        Transport transport = mailSession.getTransport("smtp");
        transport.connect(host, user, pass);
        transport.sendMessage(msg, msg.getAllRecipients());
        transport.close();
        JOptionPane.showMessageDialog(null, "Your 50% Budget has been used your reaming budget is"+ab);
}
           else{
               JOptionPane.showMessageDialog(null, "User Not Found");
           }
        }catch(Exception ex){
JOptionPane.showMessageDialog(rootPane, ex);

}  
        } 
    
       
        
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        AddExpense s = new AddExpense();
        s.send_mail();
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new RegisterForm().setVisible(true);
                new AddExpense().setVisible(true);
               
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Checkbool;
    private javax.swing.JButton jButton_AddBudg;
    private javax.swing.JButton jButton_Addexp;
    public static javax.swing.JButton jButton_PDF;
    private javax.swing.JButton jButton_ShowBud;
    public static javax.swing.JButton jButton_Showdata;
    public static javax.swing.JButton jButton_View;
    private javax.swing.JComboBox<String> jCombCat;
    private javax.swing.JComboBox<String> jCombCat1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JLabel jLabel_Avbudget;
    private javax.swing.JLabel jLabel_CalcTot;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable_DisplayExp;
    private javax.swing.JTextField jTextField_LN;
    public static javax.swing.JTextField jTextField_Showbud1;
    private javax.swing.JTextField jTextField_UN;
    public static javax.swing.JTextField jTextField_User;
    public static javax.swing.JTextField jTextField_User1;
    public static javax.swing.JTextField jTextField_User2;
    private javax.swing.JTextField jTextField_budget1;
    // End of variables declaration//GEN-END:variables

    private String format(Date date) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}

